### PR TITLE
Add link to game in README

### PR DESCRIPTION
**Pull request by jaminscript**
I was unaware that the game was playable until I saw the flappy-trump.md file in the flappy-trump folder. Adding the link here means anyone who finds this repo can play it without trawling your files.

### CODE REVIEW

**Comment by jamesevickery** [comment]
I know but I didn't originally intend for this to be seen by anyone anyway! Out of interest, what led you here?

**Comment by jaminscript** [comment]
There's a [Hacktoberfest Event](https://hacktoberfest.digitalocean.com/) running at the moment and if you make four pull requests to any repo on GitHub you get a free shirt. 

I'm starting to develop games with Phaser and so I wanted to find projects like yours to contribute to. Even though it's a trivial update, it's still a contribution 😄

**Comment by jamesevickery** [comment]
@jaminscript Thanks for the link - I'll have a go at that, have you got any tiny changes I can make on any of your repos?

I've just started using Phaser today, I never do much web stuff so thought I'd try and make a game using Phaser which ended up being Flappy Trump 😆. Would you be interested in a collaboration?

**Comment by jaminscript** [comment]
Sure! I'm currently building a website for myself (I teach Web Development professionally and don't have my own website, go figure) so will be focusing on that for the moment.

I've started following your GitHub account so I should get notifications about stuff you do, and can jump in when I have time to contribute. I can notify you later when I'm done with the site and we can start collaborating on something, even if it's just a learning experience.

As for contributions, I have an old [Phaser Game Template](https://github.com/jaminscript/game-template) that I haven't touched in a while, and it has an old copy of Phaser in the js folder. You could update that and that'll count as 1 of your 4 pull requests for the Hacktoberfest!

**Comment by jamesevickery** [comment]
@jaminscript Yeah I'll have a look at that then 😄Feel free to notify me about any projects you'd like me to have a look at either on here or by messaging me on [Twitter](https://twitter.com/jamesevickery)

**Pull request merged**
